image: leanprovercommunity/mathlib:gitpod

vscode:
  extensions:
    - jroesch.lean
    - sirmspencer.vscode-autohide
tasks:
  - init: . /home/gitpod/.profile && leanpkg configure && leanproject get-mathlib-cache && leanproject build